### ISSUE TITLE
Possible error when working with OpenShift cluster - resources get disposed when still in use

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-common#111]
Scenario: we are connected to an openshift cluster and have telemetry enabled.

If a plugin initializes its kubernetesClient in the default way despite the cluster is an openshift one (e.g `this.client = new DefaultKubernetesClient(new ConfigBuilder().build());`), the commons library will eventually create an adapted version to retrieve cluster infos for telemetry purposes. https://github.com/redhat-developer/intellij-common/blob/5786cc4faca8824dcf1ffd4d7bef5275a55d6319/src/main/java/com/redhat/devtools/intellij/common/kubernetes/ClusterHelper.java#L56

When it gets out from the try-resource, the openshift client gets disposed and, with it, also its httpClient. It seems that the httpClient the OpenShift client is using, it is also shared by our original kubernetesClient. So from this moment on, everything that our plugin will try to do (e.g. opening watches) will fail because the httpclient is terminated and it is never initialized again.

**Comment by adietish** [comment]
Closing this stale/outdated issue. It's 3y old.
