### ISSUE TITLE
IDEATrustManager does not prompt user to accept/refuse unknown certificates

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-common#212]
In #206 we moved the `IDEATrustManager` from intellij-kubernetes to commons. This move did not include the `CompositeX509ExtendedTrustManager` that was present in the original but used the one in https://github.com/Hakky54/sslcontext-kickstart instead (that the manager in intellij-kubernetes was based on). With this implementation intellij-kubernetes wasn't asking the user any more, whether he wants to accept/refuse an unknown certificate

**Comment by Hakky54** [comment]
Hi Andre, I noticed this issue and the usage of the IDEATrustManager. The library provides [InflatableX509ExtendedTrustManager](https://github.com/Hakky54/sslcontext-kickstart/blob/3137ea008d64f8a5fe81780d02a5330814a2140e/sslcontext-kickstart/src/main/java/nl/altindag/ssl/trustmanager/InflatableX509ExtendedTrustManager.java#L60) which provides the same feature. Wouldn't that be an option for you guys instead of having a custom CompositeX509ExtendedTrustManager and IDEATrustManager?

I am just jumping in here out of curiousity and checking whether I can provide help 😄

**Comment by adietish** [comment]
Hi @Hakky54
Thanks for the pointer. We were obviously using the wrong class.
We'd benefit from using your lib by using your well tested code. The drawback is to add further 200k to our lib. I guess it's worth it given the small size. Trying 😄

**Comment by Hakky54** [comment]
Ahh, I get it. I didn't know something like that exists, thank you for giving some context.  This is pretty interesting, I am bookmarking it 😄

**Comment by adietish** [comment]
@Hakky54 our impl is a bit hacky because there's no extension point nor API to smoothly integrate into jetbrains IDEA in this area. Nevertheless, the hacky bits are limited to a single method. Crossing fingers jetbrains do offer means at some point.

**Comment by Hakky54** [comment]
Yes, I just checked and I see that you replace the `mySystemManager` class field of the `ConfirmingTrustManager` using reflection with your own TrustManager. Very clever. Too bad they don't have a mechanism in place to replace the default trustmanager or append additional trustmanagers...

**Comment by adietish** [comment]
@Hakky54 thanks for the pointers. Nice find actually, thanks! This was added after I implemented our "utility". Looking into it.
Not annoyed by any of your comments at all. Enjoying the true FOSS exchange :) 
As a sidenode, we aim at supporting a wider range of IDEAs and move up the upper bound as new releases are published. We're currently at IC-2022.1+ which seems to offer this method.

**Comment by adietish** [comment]
trying to add the kubernetes-client certificates to the `MutableTrustManager` within jetbrains `ConfirmingTrustManager` is not working for me. `MutableTrustManager` spits an exception when it is initialized before my certificate would be added to it. I'll therefore stick to my current hacky implementation and revisit this once we move up the min supported IDEA version.
