### ISSUE TITLE
github action IJ-latest is failing

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-common#249]
```
Run LATEST-EAP-SNAPSHOT=$(./gradlew printProductsReleases | grep 'IC-' | head -n 1 | cut -d'-' -f2)
/home/runner/work/_temp/36567e55-e473-4b96-891b-c2df50f193e3.sh: line 1: LATEST-EAP-SNAPSHOT=243.19420.21: command not found
```

**Comment by adietish** [comment]
@sbouchet looks like our new script has a problem?

**Comment by adietish** [comment]
this was fixed by https://github.com/redhat-developer/intellij-common/commit/559a944a025168ecc91ed6b09044d0236017e59f
Closing.

**Comment by adietish** [comment]
This seems to still have issue. Reopening.

**Comment by adietish** [comment]
Latest unfortunately still fails:
```
/home/runner/work/_temp/0bdf35f6-d95e-4838-8175-e1e8019aa52e.sh: line 1: LATEST-EAP-SNAPSHOT=243.19420.21: command not found
Error: Process completed with exit code 127.
```
Reopening.

**Comment by sbouchet** [comment]
it's because when you re-try any workflows, it re-use the exact same workflow file used to run it in the first place, not the actual on main... 
it's now ok : 
https://github.com/redhat-developer/intellij-common/actions/runs/11395126029
