### ISSUE TITLE
Credentials are not used for proxies in < `IC-2024.3`

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-common#255]
See https://github.com/redhat-developer/intellij-common/pull/240#issuecomment-2452616763

**Comment by webbnh** [comment]
Pardon my intrusion, but I'm testing a feature of `sync2jira` and I'd like to see an update to this issue, so...sorry for the noise.  😇

**Comment by adietish** [comment]
Hi @webbnh 

Thanks for chiming in, you're not noise at all :)
I went unsure if this issue really exists. Can you confirm it?

**Comment by webbnh** [comment]
Hi adietish, as I mention in my direct e-mail, I don't know anything about the problem reported by this issue -- I'm just commenting to trigger the Jira update.  (Hopefully, it will work properly this time.)  😊

**Comment by adietish** [comment]
@webbnh I think that you should not even be concerned given that this repository is about a (java) library that is consumed by our (java) plugins for intellij IDEA. Sync2Jira is python so it's not a consumer of this library. Furthermore this issue here is about the IDEA platform not being able to use proxies at runtime.
